load("@rules_python//python:py_test.bzl", "py_test")
load(
    "//ostest:defs.bzl",
    "fat_image",
)
load(":lab_test.bzl", "real_cirros_lab")
load(":tcg_qemu_wrapper.bzl", "tcg_qemu_wrapper")

package(default_visibility = ["//visibility:private"])

fat_image(
    name = "server_seed",
    files = {
        "server_meta_data.json": "meta-data",
        "server_user_data.sh": "user-data",
    },
    size_mb = 34,
    tags = [
        "manual",
        "no-remote",
    ],
    volume_label = "cidata",
)

fat_image(
    name = "client_seed",
    files = {
        "client_meta_data.json": "meta-data",
        "client_user_data.sh": "user-data",
    },
    size_mb = 34,
    tags = [
        "manual",
        "no-remote",
    ],
    volume_label = "cidata",
)

tcg_qemu_wrapper(
    name = "qemu_system_x86_64_tcg",
    qemu = "//tests/integration:qemu_system_x86_64",
)

py_test(
    name = "qemu_system_x86_64_tcg_downstream_test",
    size = "medium",
    srcs = ["qemu_system_x86_64_tcg_downstream_test.py"],
    args = [
        "--qemu=$(rlocationpath :qemu_system_x86_64_tcg)",
    ],
    data = [":qemu_system_x86_64_tcg"],
    legacy_create_init = 0,
    python_version = "3.12",
    tags = [
        "manual",
        "no-remote",
    ],
    deps = ["@rules_python//python/runfiles"],
)

real_cirros_lab(
    name = "real_cirros_lab_test",
    qemu = "//tests/integration:qemu_system_x86_64",
    qemu_firmware_dir = "@qemu_noble_x86_64//:qemu_firmware_dir",
)

real_cirros_lab(
    name = "real_cirros_lab_tcg_test",
    qemu = ":qemu_system_x86_64_tcg",
    qemu_firmware_dir = "@qemu_noble_x86_64//:qemu_firmware_dir",
)
